project:
  type: manuscript

lang: de

manuscript:
  article: index.qmd

execute:
  freeze: auto

format:
  html:
    theme: flatly
    css: style.css
  pdf:
    documentclass: scrreprt
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    highlight-style: github
    mainfont: "TeX Gyre Termes"
    keep-tex: true
    output-file: nr_thesis 
#  epub:
#    theme: flatly
#    output-file: nr_thesis

